export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
  },
  WORKSPACE: {
    HOME: '/workspace',
    INBOX: '/workspace/inbox',
    SEARCH: '/workspace/search',
    AI_COPILOT: '/workspace/copilot',
    APPS: {
      HRMS: '/workspace/apps/hrms',
      PROJECTS: '/workspace/apps/projects',
      PORTFOLIO: '/workspace/apps/portfolio',
      REPORTS: '/workspace/apps/analytics',
      DOCUMENTS: '/workspace/apps/documents',
      CALENDAR: '/workspace/apps/calendar',
    },
    ADMIN: {
      ORGANIZATIONS: '/workspace/admin/organizations',
      PEOPLE: '/workspace/admin/people',
      DEPARTMENTS: '/workspace/admin/departments',
      TEAMS: '/workspace/admin/teams',
      ROLES: '/workspace/admin/roles',
      PERMISSIONS: '/workspace/admin/permissions',
      AUDIT_LOGS: '/workspace/admin/security',
    },
    PLATFORM: {
      MARKETPLACE: '/workspace/apps/marketplace',
      INTEGRATIONS: '/workspace/apps/integrations',
      API: '/workspace/platform/api',
      BILLING: '/workspace/admin/billing',
    },
    SETTINGS: '/workspace/admin/settings',
    FUTURE: {
      CRM: '/workspace/apps/crm',
      FINANCE: '/workspace/apps/finance',
      ASSETS: '/workspace/apps/assets',
      INVENTORY: '/workspace/apps/inventory',
      RECRUITMENT: '/workspace/apps/recruitment',
      PERFORMANCE: '/workspace/apps/performance',
      KNOWLEDGE: '/workspace/apps/knowledge',
      AI_AGENTS: '/workspace/apps/ai-agents',
    },
  },
  ERRORS: {
    NOT_FOUND: '/404',
    INTERNAL_SERVER_ERROR: '/500',
    BAD_GATEWAY: '/502',
  },
} as const;
